"""
Django settings for trydjango19 project.

Generated by 'django-admin startproject' using Django 2.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'k2k+!n5pxz9t)%apyw=6pr)lb0i#@-q1h#atdi#%f31!f=%=d-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


LOGIN_URL = '/login/'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'posts',
    'pagedown.apps.PagedownConfig',
    'markdown_deux',
    'crispy_forms',
    'comments',
    'rest_framework',
]

CRISPY_TEMPLATE_PACK = 'bootstrap3'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'trydjango19.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'trydjango19.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
    # '/var/www/static/',
]

STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR),'static_cdn')

MEDIA_URL='/media/'
MEDIA_ROOT = os.path.join(os.path.dirname(BASE_DIR),'media_cdn')



REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    # 'DEFAULT_PARSER_CLASSES': [
    #     'rest_framework.parsers.JSONParser',
    # ]
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        # 'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
        # 'rest_framework.authentication.BasicAuthentication'
    ],

    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],


}

# curl -X POST -d "username=admin&password=password" http://localhost:8000/api/auth/token/

# {"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6ImFkbWluIiwiZXhwIjoxNTcyNzI0ODcwLCJlbWFpbCI6IiJ9.bx5ZUP6EGC_a7_p_DqlIcyMRW7rJKIr6yRcRUYdB1DU"}

# curl -H "Authorization: JWT <your_token>" http://localhost:8000/api/comments/

# {"count":15,"next":null,"previous":null,"results":[{"url":"http://localhost:8000/api/comments/24/","id":24,"content":"reply eureka!","reply_cnt":0,"timestamp":"2019-11-02T13:32:30.214416Z"},{"url":"http://localhost:8000/api/comments/23/","id":23,"content":"eureka! x2 Voila!","reply_cnt":1,"timestamp":"2019-11-02T13:31:37.826102Z"},{"url":"http://localhost:8000/api/comments/22/","id":22,"content":"mmmmmmmmmmmmm","reply_cnt":0,"timestamp":"2019-11-02T13:28:41.553087Z"},{"url":"http://localhost:8000/api/comments/21/","id":21,"content":"eureka!","reply_cnt":0,"timestamp":"2019-11-02T13:25:55.974068Z"},{"url":"http://localhost:8000/api/comments/20/","id":20,"content":"213463461243123","reply_cnt":0,"timestamp":"2019-11-02T13:25:01.146529Z"},{"url":"http://localhost:8000/api/comments/19/","id":19,"content":"asdjksadksad","reply_cnt":0,"timestamp":"2019-11-02T10:12:21.899165Z"},{"url":"http://localhost:8000/api/comments/18/","id":18,"content":"jdaskda","reply_cnt":0,"timestamp":"2019-11-02T10:12:13.562374Z"},{"url":"http://localhost:8000/api/comments/17/","id":17,"content":"asdakjdhaks","reply_cnt":1,"timestamp":"2019-11-02T10:12:08.417548Z"},{"url":"http://localhost:8000/api/comments/16/","id":16,"content":"second reply","reply_cnt":0,"timestamp":"2019-11-02T10:01:41.422005Z"},{"url":"http://localhost:8000/api/comments/15/","id":15,"content":"first reply","reply_cnt":0,"timestamp":"2019-11-02T10:01:07.199062Z"},{"url":"http://localhost:8000/api/comments/14/","id":14,"content":"second commment","reply_cnt":2,"timestamp":"2019-11-02T10:00:53.395091Z"},{"url":"http://localhost:8000/api/comments/13/","id":13,"content":"first comment","reply_cnt":0,"timestamp":"2019-11-02T10:00:07.589196Z"},{"url":"http://localhost:8000/api/comments/12/","id":12,"content":"Nice Post","reply_cnt":0,"timestamp":"2019-10-16T09:48:10.384878Z"},{"url":"http://localhost:8000/api/comments/10/","id":10,"content":"Absolutely","reply_cnt":0,"timestamp":"2019-10-15T10:20:53.115918Z"},{"url":"http://localhost:8000/api/comments/3/","id":3,"content":"Nice movie 8/10","reply_cnt":1,"timestamp":"2019-10-15T07:00:07.483385Z"}]}

# curl http://localhost:8000/api/comments/

# {"count":15,"next":null,"previous":null,"results":[{"url":"http://localhost:8000/api/comments/24/","id":24,"content":"reply eureka!","reply_cnt":0,"timestamp":"2019-11-02T13:32:30.214416Z"},{"url":"http://localhost:8000/api/comments/23/","id":23,"content":"eureka! x2 Voila!","reply_cnt":1,"timestamp":"2019-11-02T13:31:37.826102Z"},{"url":"http://localhost:8000/api/comments/22/","id":22,"content":"mmmmmmmmmmmmm","reply_cnt":0,"timestamp":"2019-11-02T13:28:41.553087Z"},{"url":"http://localhost:8000/api/comments/21/","id":21,"content":"eureka!","reply_cnt":0,"timestamp":"2019-11-02T13:25:55.974068Z"},{"url":"http://localhost:8000/api/comments/20/","id":20,"content":"213463461243123","reply_cnt":0,"timestamp":"2019-11-02T13:25:01.146529Z"},{"url":"http://localhost:8000/api/comments/19/","id":19,"content":"asdjksadksad","reply_cnt":0,"timestamp":"2019-11-02T10:12:21.899165Z"},{"url":"http://localhost:8000/api/comments/18/","id":18,"content":"jdaskda","reply_cnt":0,"timestamp":"2019-11-02T10:12:13.562374Z"},{"url":"http://localhost:8000/api/comments/17/","id":17,"content":"asdakjdhaks","reply_cnt":1,"timestamp":"2019-11-02T10:12:08.417548Z"},{"url":"http://localhost:8000/api/comments/16/","id":16,"content":"second reply","reply_cnt":0,"timestamp":"2019-11-02T10:01:41.422005Z"},{"url":"http://localhost:8000/api/comments/15/","id":15,"content":"first reply","reply_cnt":0,"timestamp":"2019-11-02T10:01:07.199062Z"},{"url":"http://localhost:8000/api/comments/14/","id":14,"content":"second commment","reply_cnt":2,"timestamp":"2019-11-02T10:00:53.395091Z"},{"url":"http://localhost:8000/api/comments/13/","id":13,"content":"first comment","reply_cnt":0,"timestamp":"2019-11-02T10:00:07.589196Z"},{"url":"http://localhost:8000/api/comments/12/","id":12,"content":"Nice Post","reply_cnt":0,"timestamp":"2019-10-16T09:48:10.384878Z"},{"url":"http://localhost:8000/api/comments/10/","id":10,"content":"Absolutely","reply_cnt":0,"timestamp":"2019-10-15T10:20:53.115918Z"},{"url":"http://localhost:8000/api/comments/3/","id":3,"content":"Nice movie 8/10","reply_cnt":1,"timestamp":"2019-10-15T07:00:07.483385Z"}]}



